#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Socket6
Version  : 0.28
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/U/UM/UMEMOTO/Socket6-0.28.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/U/UM/UMEMOTO/Socket6-0.28.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libio-socket-inet6-perl/libio-socket-inet6-perl_2.72-2.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Socket6-lib
Requires: perl-Socket6-license
Requires: perl-Socket6-man

%description
Socket6
1. Abstract
This module supports getaddrinfo() and getnameinfo() to intend to
enable protocol independent programing.
If your environment supports IPv6, IPv6 related defines such as
AF_INET6 are included.

%package lib
Summary: lib components for the perl-Socket6 package.
Group: Libraries
Requires: perl-Socket6-license

%description lib
lib components for the perl-Socket6 package.


%package license
Summary: license components for the perl-Socket6 package.
Group: Default

%description license
license components for the perl-Socket6 package.


%package man
Summary: man components for the perl-Socket6 package.
Group: Default

%description man
man components for the perl-Socket6 package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Socket6-0.28
mkdir -p %{_topdir}/BUILD/Socket6-0.28/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Socket6-0.28/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Socket6
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Socket6/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Socket6.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Socket6/Socket6.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Socket6/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Socket6.3
